require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LowChamberAgendasController do

  # This should return the minimal set of attributes required to create a valid
  # LowChamberAgenda. As you add validations to LowChamberAgenda, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "uid" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LowChamberAgendasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all low_chamber_agendas as @low_chamber_agendas" do
      low_chamber_agenda = LowChamberAgenda.create! valid_attributes
      get :index, {}, valid_session
      assigns(:low_chamber_agendas).should eq([low_chamber_agenda])
    end
  end

  describe "GET show" do
    it "assigns the requested low_chamber_agenda as @low_chamber_agenda" do
      low_chamber_agenda = LowChamberAgenda.create! valid_attributes
      get :show, {:id => low_chamber_agenda.to_param}, valid_session
      assigns(:low_chamber_agenda).should eq(low_chamber_agenda)
    end
  end

  describe "GET new" do
    it "assigns a new low_chamber_agenda as @low_chamber_agenda" do
      get :new, {}, valid_session
      assigns(:low_chamber_agenda).should be_a_new(LowChamberAgenda)
    end
  end

  describe "GET edit" do
    it "assigns the requested low_chamber_agenda as @low_chamber_agenda" do
      low_chamber_agenda = LowChamberAgenda.create! valid_attributes
      get :edit, {:id => low_chamber_agenda.to_param}, valid_session
      assigns(:low_chamber_agenda).should eq(low_chamber_agenda)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LowChamberAgenda" do
        expect {
          post :create, {:low_chamber_agenda => valid_attributes}, valid_session
        }.to change(LowChamberAgenda, :count).by(1)
      end

      it "assigns a newly created low_chamber_agenda as @low_chamber_agenda" do
        post :create, {:low_chamber_agenda => valid_attributes}, valid_session
        assigns(:low_chamber_agenda).should be_a(LowChamberAgenda)
        assigns(:low_chamber_agenda).should be_persisted
      end

      it "redirects to the created low_chamber_agenda" do
        post :create, {:low_chamber_agenda => valid_attributes}, valid_session
        response.should redirect_to(LowChamberAgenda.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved low_chamber_agenda as @low_chamber_agenda" do
        # Trigger the behavior that occurs when invalid params are submitted
        LowChamberAgenda.any_instance.stub(:save).and_return(false)
        post :create, {:low_chamber_agenda => { "uid" => "invalid value" }}, valid_session
        assigns(:low_chamber_agenda).should be_a_new(LowChamberAgenda)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LowChamberAgenda.any_instance.stub(:save).and_return(false)
        post :create, {:low_chamber_agenda => { "uid" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested low_chamber_agenda" do
        low_chamber_agenda = LowChamberAgenda.create! valid_attributes
        # Assuming there are no other low_chamber_agendas in the database, this
        # specifies that the LowChamberAgenda created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LowChamberAgenda.any_instance.should_receive(:update_attributes).with({ "uid" => "MyString" })
        put :update, {:id => low_chamber_agenda.to_param, :low_chamber_agenda => { "uid" => "MyString" }}, valid_session
      end

      it "assigns the requested low_chamber_agenda as @low_chamber_agenda" do
        low_chamber_agenda = LowChamberAgenda.create! valid_attributes
        put :update, {:id => low_chamber_agenda.to_param, :low_chamber_agenda => valid_attributes}, valid_session
        assigns(:low_chamber_agenda).should eq(low_chamber_agenda)
      end

      it "redirects to the low_chamber_agenda" do
        low_chamber_agenda = LowChamberAgenda.create! valid_attributes
        put :update, {:id => low_chamber_agenda.to_param, :low_chamber_agenda => valid_attributes}, valid_session
        response.should redirect_to(low_chamber_agenda)
      end
    end

    describe "with invalid params" do
      it "assigns the low_chamber_agenda as @low_chamber_agenda" do
        low_chamber_agenda = LowChamberAgenda.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LowChamberAgenda.any_instance.stub(:save).and_return(false)
        put :update, {:id => low_chamber_agenda.to_param, :low_chamber_agenda => { "uid" => "invalid value" }}, valid_session
        assigns(:low_chamber_agenda).should eq(low_chamber_agenda)
      end

      it "re-renders the 'edit' template" do
        low_chamber_agenda = LowChamberAgenda.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LowChamberAgenda.any_instance.stub(:save).and_return(false)
        put :update, {:id => low_chamber_agenda.to_param, :low_chamber_agenda => { "uid" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested low_chamber_agenda" do
      low_chamber_agenda = LowChamberAgenda.create! valid_attributes
      expect {
        delete :destroy, {:id => low_chamber_agenda.to_param}, valid_session
      }.to change(LowChamberAgenda, :count).by(-1)
    end

    it "redirects to the low_chamber_agendas list" do
      low_chamber_agenda = LowChamberAgenda.create! valid_attributes
      delete :destroy, {:id => low_chamber_agenda.to_param}, valid_session
      response.should redirect_to(low_chamber_agendas_url)
    end
  end

end
